/* Autogenerated code by MGen for JavaScript */

/*jshint -W069 */ // Turn of lint warnings for accessing a property using a string literal with square bracket notation.

var mgen_classreg = {}; // this variable name can be changed with the setting: classregistry_name

(function(registry){
	"use strict";

	registry.classRegistry = {};
	registry.hashRegistry = function(typeId16Bit){
		switch(typeId16Bit[0]){
			case "Ntk":
				switch(typeId16Bit[1]){
					case "Ksk":
						switch osv osv...
				}
			return "gameworld.types.basemodule1.Car"
		}
		return null
	}

	registry.classRegistry["gameworld.types.basemodule1.Car"] = {
		"typeId16Bit": ["Ntk", "Ksk", "L20"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		},
		"topSpeed": {
			"flags": ["required"],
			"type": "int32",
			"hash": "48M"
		},
		"brand": {
			"flags": ["required"],
			"type": "string",
			"hash": "SxI"
		},
		"nWheels": {
			"flags": [],
			"type": "int8",
			"hash": "Rsc"
		}
	};

	if(registry.hashRegistry["Ksk"]) throw "name conflict in gameworld.types.basemodule1.Vehicle";
	registry.hashRegistry["Ksk"] = "gameworld.types.basemodule1.Vehicle";
	registry.classRegistry["gameworld.types.basemodule1.Vehicle"] = {
		"typeId16Bit": ["Ntk", "Ksk"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		},
		"topSpeed": {
			"flags": ["required"],
			"type": "int32",
			"hash": "48M"
		}
	};

	if(registry.hashRegistry["Ntk"]) throw "name conflict in gameworld.types.basemodule1.Entity";
	registry.hashRegistry["Ntk"] = "gameworld.types.basemodule1.Entity";
	registry.classRegistry["gameworld.types.basemodule1.Entity"] = {
		"typeId16Bit": ["Ntk"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		}
	};

})(mgen_classreg);
