package se.culvertsoft.mgen.jspack.generator

import se.culvertsoft.mgen.compiler.internal.BuiltInGeneratorUtil._
import se.culvertsoft.mgen.compiler.util.SuperStringBuffer
import scala.collection.JavaConversions._

object MkIntro {

  def apply(settings: java.util.Map[String, String])(implicit txtBuffer: SuperStringBuffer) = {

    val classregistryBlueprint = settings.getOrElse("classregistryblueprint", "blueprint")

    ln("/* Autogenerated code by MGen for JavaScript */")
    ln("")
    ln("/*jshint -W069 */ // Turn of lint warnings for accessing a property using a string literal with square bracket notation.")
    ln("(function(){")
    txtBuffer {        
      ln("\"use strict\";")
      ln("var blueprint = {};")
      ln("")
    }
  }
}