/* Autogenerated code by MGen for JavaScript */

/*jshint -W069 */ // Turn of lint warnings for accessing a property using a string literal with square bracket notation.

var mgen_classreg = {}; // this variable name can be changed with the setting: classregistry_name

(function(registry){
	"use strict";

	registry.classRegistry = {};
	registry.hashRegistry = {};

	if(registry.hashRegistry["pKg"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.SimpleType";
	registry.hashRegistry["pKg"] = "se.culvertsoft.mgen.visualdesigner.model.SimpleType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.SimpleType"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg"],

	};

	if(registry.hashRegistry["09I"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.GenericType";
	registry.hashRegistry["09I"] = "se.culvertsoft.mgen.visualdesigner.model.GenericType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.GenericType"] = {
		"mGenTypeHash": ["BSI", "k78", "09I"],

	};

	if(registry.hashRegistry["9B4"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.ListOrArrayType";
	registry.hashRegistry["9B4"] = "se.culvertsoft.mgen.visualdesigner.model.ListOrArrayType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.ListOrArrayType"] = {
		"mGenTypeHash": ["BSI", "k78", "09I", "9B4"],
		"elementType": {
			"flags": ["polymorphic"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.FieldType",
			"hash": "B30"
		}
	};

	if(registry.hashRegistry["6tE"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Module";
	registry.hashRegistry["6tE"] = "se.culvertsoft.mgen.visualdesigner.model.Module";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Module"] = {
		"mGenTypeHash": ["OQA", "uXw", "6tE"],
		"id": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "gJ8"
		},
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"parent": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "MbE"
		},
		"placement": {
			"flags": ["required"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.Placement",
			"hash": "iVc"
		},
		"settings": {
			"flags": [],
			"type": "map:string:string",
			"hash": "osE"
		},
		"submodules": {
			"flags": [],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.Module",
			"hash": "qL4"
		},
		"types": {
			"flags": [],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.CustomType",
			"hash": "Vq0"
		}
	};

	if(registry.hashRegistry["IY4"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Placement";
	registry.hashRegistry["IY4"] = "se.culvertsoft.mgen.visualdesigner.model.Placement";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Placement"] = {
		"mGenTypeHash": ["IY4"],
		"x": {
			"flags": [],
			"type": "int32",
			"hash": "Hm8"
		},
		"y": {
			"flags": [],
			"type": "int32",
			"hash": "Dk4"
		},
		"width": {
			"flags": [],
			"type": "int32",
			"hash": "r2M"
		},
		"height": {
			"flags": [],
			"type": "int32",
			"hash": "bg8"
		}
	};

	if(registry.hashRegistry["Es0"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Int8Type";
	registry.hashRegistry["Es0"] = "se.culvertsoft.mgen.visualdesigner.model.Int8Type";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Int8Type"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8", "Es0"],

	};

	if(registry.hashRegistry["Kh8"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.PrimitiveType";
	registry.hashRegistry["Kh8"] = "se.culvertsoft.mgen.visualdesigner.model.PrimitiveType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.PrimitiveType"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8"],

	};

	if(registry.hashRegistry["NtA"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Int64Type";
	registry.hashRegistry["NtA"] = "se.culvertsoft.mgen.visualdesigner.model.Int64Type";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Int64Type"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8", "NtA"],

	};

	if(registry.hashRegistry["ETU"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.ListType";
	registry.hashRegistry["ETU"] = "se.culvertsoft.mgen.visualdesigner.model.ListType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.ListType"] = {
		"mGenTypeHash": ["BSI", "k78", "09I", "9B4", "ETU"],
		"elementType": {
			"flags": ["polymorphic"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.FieldType",
			"hash": "B30"
		}
	};

	if(registry.hashRegistry["ORE"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.BoolType";
	registry.hashRegistry["ORE"] = "se.culvertsoft.mgen.visualdesigner.model.BoolType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.BoolType"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8", "ORE"],

	};

	if(registry.hashRegistry["LUA"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Project";
	registry.hashRegistry["LUA"] = "se.culvertsoft.mgen.visualdesigner.model.Project";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Project"] = {
		"mGenTypeHash": ["OQA", "LUA"],
		"id": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "gJ8"
		},
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"parent": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "MbE"
		},
		"generators": {
			"flags": ["required"],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.Generator",
			"hash": "gmk"
		},
		"settings": {
			"flags": [],
			"type": "map:string:string",
			"hash": "osE"
		},
		"subprojects": {
			"flags": [],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.Project",
			"hash": "CPY"
		},
		"modules": {
			"flags": [],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.Module",
			"hash": "CA4"
		}
	};

	if(registry.hashRegistry["O6c"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.NoType";
	registry.hashRegistry["O6c"] = "se.culvertsoft.mgen.visualdesigner.model.NoType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.NoType"] = {
		"mGenTypeHash": ["BSI", "k78", "O6c"],

	};

	if(registry.hashRegistry["k78"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.BuiltInType";
	registry.hashRegistry["k78"] = "se.culvertsoft.mgen.visualdesigner.model.BuiltInType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.BuiltInType"] = {
		"mGenTypeHash": ["BSI", "k78"],

	};

	if(registry.hashRegistry["Gs4"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.ArrayType";
	registry.hashRegistry["Gs4"] = "se.culvertsoft.mgen.visualdesigner.model.ArrayType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.ArrayType"] = {
		"mGenTypeHash": ["BSI", "k78", "09I", "9B4", "Gs4"],
		"elementType": {
			"flags": ["polymorphic"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.FieldType",
			"hash": "B30"
		}
	};

	if(registry.hashRegistry["mzI"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.CustomTypeField";
	registry.hashRegistry["mzI"] = "se.culvertsoft.mgen.visualdesigner.model.CustomTypeField";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.CustomTypeField"] = {
		"mGenTypeHash": ["OQA", "mzI"],
		"id": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "gJ8"
		},
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"parent": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "MbE"
		},
		"type": {
			"flags": ["required"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.FieldType",
			"hash": "foc"
		},
		"flags": {
			"flags": [],
			"type": "list:string",
			"hash": "o6c"
		}
	};

	if(registry.hashRegistry["eH4"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.CustomType";
	registry.hashRegistry["eH4"] = "se.culvertsoft.mgen.visualdesigner.model.CustomType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.CustomType"] = {
		"mGenTypeHash": ["OQA", "uXw", "eH4"],
		"id": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "gJ8"
		},
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"parent": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "MbE"
		},
		"placement": {
			"flags": ["required"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.Placement",
			"hash": "iVc"
		},
		"superType": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "ais"
		},
		"subTypes": {
			"flags": [],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "L8w"
		},
		"fields": {
			"flags": [],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.CustomTypeField",
			"hash": "784"
		}
	};

	if(registry.hashRegistry["BSI"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.FieldType";
	registry.hashRegistry["BSI"] = "se.culvertsoft.mgen.visualdesigner.model.FieldType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.FieldType"] = {
		"mGenTypeHash": ["BSI"],

	};

	if(registry.hashRegistry["lsI"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Generator";
	registry.hashRegistry["lsI"] = "se.culvertsoft.mgen.visualdesigner.model.Generator";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Generator"] = {
		"mGenTypeHash": ["lsI"],
		"name": {
			"flags": ["required"],
			"type": "string",
			"hash": "kmY"
		},
		"generatorClassName": {
			"flags": ["required"],
			"type": "string",
			"hash": "0Ec"
		},
		"generatorJarFileFolder": {
			"flags": ["required"],
			"type": "string",
			"hash": "6wk"
		},
		"outputFolder": {
			"flags": ["required"],
			"type": "string",
			"hash": "Eok"
		},
		"settings": {
			"flags": [],
			"type": "map:string:string",
			"hash": "osE"
		}
	};

	if(registry.hashRegistry["nmc"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.StringType";
	registry.hashRegistry["nmc"] = "se.culvertsoft.mgen.visualdesigner.model.StringType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.StringType"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "nmc"],

	};

	if(registry.hashRegistry["uhI"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Int16Type";
	registry.hashRegistry["uhI"] = "se.culvertsoft.mgen.visualdesigner.model.Int16Type";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Int16Type"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8", "uhI"],

	};

	if(registry.hashRegistry["uFQ"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Int32Type";
	registry.hashRegistry["uFQ"] = "se.culvertsoft.mgen.visualdesigner.model.Int32Type";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Int32Type"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8", "uFQ"],

	};

	if(registry.hashRegistry["uXw"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.PlacedEntity";
	registry.hashRegistry["uXw"] = "se.culvertsoft.mgen.visualdesigner.model.PlacedEntity";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.PlacedEntity"] = {
		"mGenTypeHash": ["OQA", "uXw"],
		"id": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "gJ8"
		},
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"parent": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "MbE"
		},
		"placement": {
			"flags": ["required"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.Placement",
			"hash": "iVc"
		}
	};

	if(registry.hashRegistry["Igs"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Float32Type";
	registry.hashRegistry["Igs"] = "se.culvertsoft.mgen.visualdesigner.model.Float32Type";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Float32Type"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8", "Igs"],

	};

	if(registry.hashRegistry["ku4"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.CustomTypeRef";
	registry.hashRegistry["ku4"] = "se.culvertsoft.mgen.visualdesigner.model.CustomTypeRef";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.CustomTypeRef"] = {
		"mGenTypeHash": ["BSI", "ku4"],
		"id": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "gJ8"
		}
	};

	if(registry.hashRegistry["qXc"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.MapType";
	registry.hashRegistry["qXc"] = "se.culvertsoft.mgen.visualdesigner.model.MapType";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.MapType"] = {
		"mGenTypeHash": ["BSI", "k78", "09I", "qXc"],
		"keyType": {
			"flags": ["polymorphic"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.SimpleType",
			"hash": "bRE"
		},
		"valueType": {
			"flags": ["polymorphic"],
			"type": "se.culvertsoft.mgen.visualdesigner.model.FieldType",
			"hash": "MyQ"
		}
	};

	if(registry.hashRegistry["+LY"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.ClipboardContents";
	registry.hashRegistry["+LY"] = "se.culvertsoft.mgen.visualdesigner.model.ClipboardContents";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.ClipboardContents"] = {
		"mGenTypeHash": ["+LY"],
		"items": {
			"flags": ["required"],
			"type": "list:se.culvertsoft.mgen.visualdesigner.model.Entity",
			"hash": "azE"
		}
	};

	if(registry.hashRegistry["rI8"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Float64Type";
	registry.hashRegistry["rI8"] = "se.culvertsoft.mgen.visualdesigner.model.Float64Type";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Float64Type"] = {
		"mGenTypeHash": ["BSI", "k78", "pKg", "Kh8", "rI8"],

	};

	if(registry.hashRegistry["JHs"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.EntityId";
	registry.hashRegistry["JHs"] = "se.culvertsoft.mgen.visualdesigner.model.EntityId";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.EntityId"] = {
		"mGenTypeHash": ["JHs"],
		"lsb": {
			"flags": ["required"],
			"type": "int64",
			"hash": "M3g"
		},
		"msb": {
			"flags": ["required"],
			"type": "int64",
			"hash": "BEg"
		}
	};

	if(registry.hashRegistry["OQA"]) throw "name conflict in se.culvertsoft.mgen.visualdesigner.model.Entity";
	registry.hashRegistry["OQA"] = "se.culvertsoft.mgen.visualdesigner.model.Entity";
	registry.classRegistry["se.culvertsoft.mgen.visualdesigner.model.Entity"] = {
		"mGenTypeHash": ["OQA"],
		"id": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "gJ8"
		},
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"parent": {
			"flags": [],
			"type": "se.culvertsoft.mgen.visualdesigner.model.EntityId",
			"hash": "MbE"
		}
	};

})(mgen_classreg);
