all: 	
	#########################################
	#	BUILDING MGEN-JAVAGENERATOR	#
	#########################################
	sbt compile package publish-local

clean: 	
	#########################################
	#	CLEANING MGEN-JAVAGENERATOR	#
	#########################################
	sbt clean

