all: 	
	#########################################
	#   BUILDING MGEN-JAVAGENERATOR         #
	#########################################
	sbt compile package publish-local

eclipse:
	###################################################
	# CREATING ECLIPSE PROJECT FOR MGEN-JAVAGENERATOR #
	###################################################
	sbt eclipse

clean: 	
	#########################################
	#   CLEANING MGEN-JAVAGENERATOR         #
	#########################################
	sbt clean

doc:
	#########################################
	#  DOCUMENTATION MGEN-JAVAGENERATOR     #
	#########################################
	sbt doc
        
run-tests:
	#######################################
	#      TESTING MGEN-JAVAGENERATOR     #
	#######################################
    #NOT_YET_IMPLEMENTED#
