all: 	
	########################################
	#   BUILDING MGEN-JAVASCRIPTGENERATOR  #
	########################################
	sbt compile package publish-local

eclipse:
	#########################################################
	# CREATING ECLIPSE PROJECT FOR MGEN-JAVASCRIPTGENERATOR #
	#########################################################
	sbt eclipse

clean: 	
	########################################
	#   CLEANING MGEN-JAVASCRIPTGENERATOR  #
	########################################
	sbt clean