all: 	
	########################################
	#   BUILDING MGEN-JAVASCRIPTGENERATOR  #
	########################################
	sbt compile package publish-local

eclipse:
	#########################################################
	# CREATING ECLIPSE PROJECT FOR MGEN-JAVASCRIPTGENERATOR #
	#########################################################
	sbt eclipse

clean: 	
	########################################
	#   CLEANING MGEN-JAVASCRIPTGENERATOR  #
	########################################
	sbt clean

doc:
	#############################################
	#  DOCUMENTATION MGEN-JAVASCRIPTGENERATOR   #
	#############################################
	sbt doc	

run-tests:
	##########################################
	#     TESTING MGEN-JAVASCRIPTGENERATOR   #
	##########################################
    #NOT_YET_IMPLEMENTED#
	