all: 	
	#########################################
	#	    BUILDING MGEN-API		#
	#########################################
	sbt compile package publish-local

clean: 	
	#########################################
	#	    CLEANING MGEN-API		#
	#########################################
	sbt clean

