
generate:
	cd depends && make generate
	cd write && make generate
	cd read && make generate
	
eclipse:
	cd depends && make eclipse
	cd write && make eclipse
	cd read && make eclipse
	
clean:
	cd depends && make clean
	cd write && make clean
	cd read && make clean
