/* Autogenerated code by MGen for JavaScript */

/*jshint -W069 */ // Turn of lint warnings for accessing a property using a string literal with square bracket notation.

var mgen_classreg = {}; // this variable name can be changed with the setting: classregistry_name

(function(registry){
	"use strict";

	registry.classRegistry = {};
	registry.hashRegistry = {};

	if(registry.hashRegistry["L20"]) throw "name conflict in gameworld.types.basemodule1.Car";
	registry.hashRegistry["L20"] = "gameworld.types.basemodule1.Car";
	registry.classRegistry["gameworld.types.basemodule1.Car"] = {
		"mGenTypeHash": ["Ntk", "Ksk", "L20"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		},
		"topSpeed": {
			"flags": ["required"],
			"type": "int32",
			"hash": "48M"
		},
		"brand": {
			"flags": ["required"],
			"type": "string",
			"hash": "SxI"
		},
		"nWheels": {
			"flags": [],
			"type": "int8",
			"hash": "Rsc"
		}
	};

	if(registry.hashRegistry["NHU"]) throw "name conflict in gameworld.types.basemodule1.Positioning";
	registry.hashRegistry["NHU"] = "gameworld.types.basemodule1.Positioning";
	registry.classRegistry["gameworld.types.basemodule1.Positioning"] = {
		"mGenTypeHash": ["NHU"],
		"position": {
			"flags": ["required"],
			"type": "gameworld.types.basemodule1.VectorR3",
			"hash": "mR8"
		},
		"velocity": {
			"flags": ["optional"],
			"type": "gameworld.types.basemodule1.VectorR3",
			"hash": "D00"
		},
		"acceleration": {
			"flags": ["polymorphic","optional"],
			"type": "gameworld.types.basemodule1.VectorR3",
			"hash": "5+k"
		}
	};

	if(registry.hashRegistry["X1o"]) throw "name conflict in gameworld.types.basemodule1.Item";
	registry.hashRegistry["X1o"] = "gameworld.types.basemodule1.Item";
	registry.classRegistry["gameworld.types.basemodule1.Item"] = {
		"mGenTypeHash": ["Ntk", "X1o"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		}
	};

	if(registry.hashRegistry["auw"]) throw "name conflict in gameworld.types.basemodule1.Creature";
	registry.hashRegistry["auw"] = "gameworld.types.basemodule1.Creature";
	registry.classRegistry["gameworld.types.basemodule1.Creature"] = {
		"mGenTypeHash": ["Ntk", "auw"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		},
		"hp": {
			"flags": [],
			"type": "int16",
			"hash": "4Rs"
		}
	};

	if(registry.hashRegistry["J8g"]) throw "name conflict in gameworld.types.basemodule1.VectorR3";
	registry.hashRegistry["J8g"] = "gameworld.types.basemodule1.VectorR3";
	registry.classRegistry["gameworld.types.basemodule1.VectorR3"] = {
		"mGenTypeHash": ["J8g"],
		"x": {
			"flags": [],
			"type": "int32",
			"hash": "Hm8"
		},
		"y": {
			"flags": [],
			"type": "float32",
			"hash": "Dk4"
		},
		"z": {
			"flags": [],
			"type": "float64",
			"hash": "Pi0"
		}
	};

	if(registry.hashRegistry["3cU"]) throw "name conflict in gameworld.types.basemodule1.EntityHolder";
	registry.hashRegistry["3cU"] = "gameworld.types.basemodule1.EntityHolder";
	registry.classRegistry["gameworld.types.basemodule1.EntityHolder"] = {
		"mGenTypeHash": ["3cU"],
		"entity": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Entity",
			"hash": "YiA"
		}
	};

	if(registry.hashRegistry["0mo"]) throw "name conflict in gameworld.types.basemodule1.Matrix4x4d";
	registry.hashRegistry["0mo"] = "gameworld.types.basemodule1.Matrix4x4d";
	registry.classRegistry["gameworld.types.basemodule1.Matrix4x4d"] = {
		"mGenTypeHash": ["0mo"],
		"values": {
			"flags": [],
			"type": "list:list:float64",
			"hash": "6tM"
		}
	};

	if(registry.hashRegistry["5rA"]) throw "name conflict in gameworld.types.basemodule1.World";
	registry.hashRegistry["5rA"] = "gameworld.types.basemodule1.World";
	registry.classRegistry["gameworld.types.basemodule1.World"] = {
		"mGenTypeHash": ["5rA"],
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"entities": {
			"flags": [],
			"type": "map:int64:gameworld.types.basemodule1.Entity",
			"hash": "sGI"
		},
		"loadedFromDataBase": {
			"flags": ["polymorphic","optional"],
			"type": "string",
			"hash": "zbI"
		}
	};

	if(registry.hashRegistry["JGs"]) throw "name conflict in gameworld.types.basemodule1.GarageViewer";
	registry.hashRegistry["JGs"] = "gameworld.types.basemodule1.GarageViewer";
	registry.classRegistry["gameworld.types.basemodule1.GarageViewer"] = {
		"mGenTypeHash": ["JGs"],
		"vehicles": {
			"flags": ["nonpolymorphic"],
			"type": "list:gameworld.types.basemodule1.Vehicle",
			"hash": "vpE"
		}
	};

	if(registry.hashRegistry["Ksk"]) throw "name conflict in gameworld.types.basemodule1.Vehicle";
	registry.hashRegistry["Ksk"] = "gameworld.types.basemodule1.Vehicle";
	registry.classRegistry["gameworld.types.basemodule1.Vehicle"] = {
		"mGenTypeHash": ["Ntk", "Ksk"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		},
		"topSpeed": {
			"flags": ["required"],
			"type": "int32",
			"hash": "48M"
		}
	};

	if(registry.hashRegistry["Ntk"]) throw "name conflict in gameworld.types.basemodule1.Entity";
	registry.hashRegistry["Ntk"] = "gameworld.types.basemodule1.Entity";
	registry.classRegistry["gameworld.types.basemodule1.Entity"] = {
		"mGenTypeHash": ["Ntk"],
		"id": {
			"flags": [],
			"type": "int64",
			"hash": "gJ8"
		},
		"positioning": {
			"flags": [],
			"type": "gameworld.types.basemodule1.Positioning",
			"hash": "xHs"
		}
	};

})(mgen_classreg);
