all: 	
	#########################################
	#	  BUILDING MGEN-JAVALIB		#
	#########################################
	sbt compile package publish-local

eclipse:
	#############################################
	# CREATING ECLIPSE PROJECT FOR MGEN-JAVALIB #
	#############################################
	sbt eclipse

clean: 	
	#########################################
	#	  CLEANING MGEN-JAVALIB		#
	#########################################
	sbt clean

