all: 	
	#########################################
	#   BUILDING MGEN-CPPGENERATOR          #
	#########################################
	sbt compile package publish-local

eclipse:
	##################################################
	# CREATING ECLIPSE PROJECT FOR MGEN-CPPGENERATOR #
	##################################################
	sbt eclipse

clean: 	
	#########################################
	#   CLEANING MGEN-CPPGENERATOR          #
	#########################################
	sbt clean

doc:
	#########################################
	#  DOCUMENTATION MGEN-CPPGENERATOR      #
	#########################################
	sbt doc
    
run-tests:
	#######################################
	#      TESTING MGEN-CPPGENERATOR      #
	#######################################
    #NOT_YET_IMPLEMENTED#
    