all: 	
	#########################################
	#	BUILDING MGEN-CPPGENERATOR	#
	#########################################
	sbt compile package publish-local

clean: 	
	#########################################
	#	CLEANING MGEN-CPPGENERATOR	#
	#########################################
	sbt clean

